/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumesIndexRouteImport } from './routes/resumes/index'
import { Route as CoverLetterIndexRouteImport } from './routes/cover-letter/index'
import { Route as ApplicationsIndexRouteImport } from './routes/applications/index'
import { Route as CoverLetterGenerateRouteImport } from './routes/cover-letter/generate'
import { Route as ResumesAnalyzeIndexRouteImport } from './routes/resumes/analyze/index'
import { Route as ResumesResumeIdIndexRouteImport } from './routes/resumes/$resumeId/index'
import { Route as InterviewSessionsIndexRouteImport } from './routes/interview/sessions/index'
import { Route as CoverLetterCoverLetterIdIndexRouteImport } from './routes/cover-letter/$coverLetterId/index'
import { Route as ApplicationsNewIndexRouteImport } from './routes/applications/new/index'
import { Route as ApplicationsApplicationIdIndexRouteImport } from './routes/applications/$applicationId/index'
import { Route as authVerifyIndexRouteImport } from './routes/(auth)/verify/index'
import { Route as authRegisterIndexRouteImport } from './routes/(auth)/register/index'
import { Route as authLoginIndexRouteImport } from './routes/(auth)/login/index'
import { Route as authForgotPasswordIndexRouteImport } from './routes/(auth)/forgot-password/index'
import { Route as CoverLetterCoverLetterIdEditRouteImport } from './routes/cover-letter/$coverLetterId/edit'
import { Route as ApplicationsApplicationIdEditRouteImport } from './routes/applications/$applicationId/edit'
import { Route as authResetPasswordTokenRouteImport } from './routes/(auth)/reset-password/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesIndexRoute = ResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterIndexRoute = CoverLetterIndexRouteImport.update({
  id: '/cover-letter/',
  path: '/cover-letter/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterGenerateRoute = CoverLetterGenerateRouteImport.update({
  id: '/cover-letter/generate',
  path: '/cover-letter/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesAnalyzeIndexRoute = ResumesAnalyzeIndexRouteImport.update({
  id: '/resumes/analyze/',
  path: '/resumes/analyze/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesResumeIdIndexRoute = ResumesResumeIdIndexRouteImport.update({
  id: '/resumes/$resumeId/',
  path: '/resumes/$resumeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewSessionsIndexRoute = InterviewSessionsIndexRouteImport.update({
  id: '/interview/sessions/',
  path: '/interview/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterCoverLetterIdIndexRoute =
  CoverLetterCoverLetterIdIndexRouteImport.update({
    id: '/cover-letter/$coverLetterId/',
    path: '/cover-letter/$coverLetterId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsNewIndexRoute = ApplicationsNewIndexRouteImport.update({
  id: '/applications/new/',
  path: '/applications/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdIndexRoute =
  ApplicationsApplicationIdIndexRouteImport.update({
    id: '/applications/$applicationId/',
    path: '/applications/$applicationId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const authVerifyIndexRoute = authVerifyIndexRouteImport.update({
  id: '/(auth)/verify/',
  path: '/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterIndexRoute = authRegisterIndexRouteImport.update({
  id: '/(auth)/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginIndexRoute = authLoginIndexRouteImport.update({
  id: '/(auth)/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordIndexRoute = authForgotPasswordIndexRouteImport.update({
  id: '/(auth)/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterCoverLetterIdEditRoute =
  CoverLetterCoverLetterIdEditRouteImport.update({
    id: '/cover-letter/$coverLetterId/edit',
    path: '/cover-letter/$coverLetterId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApplicationsApplicationIdEditRoute =
  ApplicationsApplicationIdEditRouteImport.update({
    id: '/applications/$applicationId/edit',
    path: '/applications/$applicationId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)
const authResetPasswordTokenRoute = authResetPasswordTokenRouteImport.update({
  id: '/(auth)/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cover-letter/generate': typeof CoverLetterGenerateRoute
  '/applications': typeof ApplicationsIndexRoute
  '/cover-letter': typeof CoverLetterIndexRoute
  '/resumes': typeof ResumesIndexRoute
  '/reset-password/$token': typeof authResetPasswordTokenRoute
  '/applications/$applicationId/edit': typeof ApplicationsApplicationIdEditRoute
  '/cover-letter/$coverLetterId/edit': typeof CoverLetterCoverLetterIdEditRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/verify': typeof authVerifyIndexRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdIndexRoute
  '/applications/new': typeof ApplicationsNewIndexRoute
  '/cover-letter/$coverLetterId': typeof CoverLetterCoverLetterIdIndexRoute
  '/interview/sessions': typeof InterviewSessionsIndexRoute
  '/resumes/$resumeId': typeof ResumesResumeIdIndexRoute
  '/resumes/analyze': typeof ResumesAnalyzeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cover-letter/generate': typeof CoverLetterGenerateRoute
  '/applications': typeof ApplicationsIndexRoute
  '/cover-letter': typeof CoverLetterIndexRoute
  '/resumes': typeof ResumesIndexRoute
  '/reset-password/$token': typeof authResetPasswordTokenRoute
  '/applications/$applicationId/edit': typeof ApplicationsApplicationIdEditRoute
  '/cover-letter/$coverLetterId/edit': typeof CoverLetterCoverLetterIdEditRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/login': typeof authLoginIndexRoute
  '/register': typeof authRegisterIndexRoute
  '/verify': typeof authVerifyIndexRoute
  '/applications/$applicationId': typeof ApplicationsApplicationIdIndexRoute
  '/applications/new': typeof ApplicationsNewIndexRoute
  '/cover-letter/$coverLetterId': typeof CoverLetterCoverLetterIdIndexRoute
  '/interview/sessions': typeof InterviewSessionsIndexRoute
  '/resumes/$resumeId': typeof ResumesResumeIdIndexRoute
  '/resumes/analyze': typeof ResumesAnalyzeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cover-letter/generate': typeof CoverLetterGenerateRoute
  '/applications/': typeof ApplicationsIndexRoute
  '/cover-letter/': typeof CoverLetterIndexRoute
  '/resumes/': typeof ResumesIndexRoute
  '/(auth)/reset-password/$token': typeof authResetPasswordTokenRoute
  '/applications/$applicationId/edit': typeof ApplicationsApplicationIdEditRoute
  '/cover-letter/$coverLetterId/edit': typeof CoverLetterCoverLetterIdEditRoute
  '/(auth)/forgot-password/': typeof authForgotPasswordIndexRoute
  '/(auth)/login/': typeof authLoginIndexRoute
  '/(auth)/register/': typeof authRegisterIndexRoute
  '/(auth)/verify/': typeof authVerifyIndexRoute
  '/applications/$applicationId/': typeof ApplicationsApplicationIdIndexRoute
  '/applications/new/': typeof ApplicationsNewIndexRoute
  '/cover-letter/$coverLetterId/': typeof CoverLetterCoverLetterIdIndexRoute
  '/interview/sessions/': typeof InterviewSessionsIndexRoute
  '/resumes/$resumeId/': typeof ResumesResumeIdIndexRoute
  '/resumes/analyze/': typeof ResumesAnalyzeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cover-letter/generate'
    | '/applications'
    | '/cover-letter'
    | '/resumes'
    | '/reset-password/$token'
    | '/applications/$applicationId/edit'
    | '/cover-letter/$coverLetterId/edit'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify'
    | '/applications/$applicationId'
    | '/applications/new'
    | '/cover-letter/$coverLetterId'
    | '/interview/sessions'
    | '/resumes/$resumeId'
    | '/resumes/analyze'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cover-letter/generate'
    | '/applications'
    | '/cover-letter'
    | '/resumes'
    | '/reset-password/$token'
    | '/applications/$applicationId/edit'
    | '/cover-letter/$coverLetterId/edit'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify'
    | '/applications/$applicationId'
    | '/applications/new'
    | '/cover-letter/$coverLetterId'
    | '/interview/sessions'
    | '/resumes/$resumeId'
    | '/resumes/analyze'
  id:
    | '__root__'
    | '/'
    | '/cover-letter/generate'
    | '/applications/'
    | '/cover-letter/'
    | '/resumes/'
    | '/(auth)/reset-password/$token'
    | '/applications/$applicationId/edit'
    | '/cover-letter/$coverLetterId/edit'
    | '/(auth)/forgot-password/'
    | '/(auth)/login/'
    | '/(auth)/register/'
    | '/(auth)/verify/'
    | '/applications/$applicationId/'
    | '/applications/new/'
    | '/cover-letter/$coverLetterId/'
    | '/interview/sessions/'
    | '/resumes/$resumeId/'
    | '/resumes/analyze/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoverLetterGenerateRoute: typeof CoverLetterGenerateRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
  CoverLetterIndexRoute: typeof CoverLetterIndexRoute
  ResumesIndexRoute: typeof ResumesIndexRoute
  authResetPasswordTokenRoute: typeof authResetPasswordTokenRoute
  ApplicationsApplicationIdEditRoute: typeof ApplicationsApplicationIdEditRoute
  CoverLetterCoverLetterIdEditRoute: typeof CoverLetterCoverLetterIdEditRoute
  authForgotPasswordIndexRoute: typeof authForgotPasswordIndexRoute
  authLoginIndexRoute: typeof authLoginIndexRoute
  authRegisterIndexRoute: typeof authRegisterIndexRoute
  authVerifyIndexRoute: typeof authVerifyIndexRoute
  ApplicationsApplicationIdIndexRoute: typeof ApplicationsApplicationIdIndexRoute
  ApplicationsNewIndexRoute: typeof ApplicationsNewIndexRoute
  CoverLetterCoverLetterIdIndexRoute: typeof CoverLetterCoverLetterIdIndexRoute
  InterviewSessionsIndexRoute: typeof InterviewSessionsIndexRoute
  ResumesResumeIdIndexRoute: typeof ResumesResumeIdIndexRoute
  ResumesAnalyzeIndexRoute: typeof ResumesAnalyzeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/': {
      id: '/resumes/'
      path: '/resumes'
      fullPath: '/resumes'
      preLoaderRoute: typeof ResumesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter/': {
      id: '/cover-letter/'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof CoverLetterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/': {
      id: '/applications/'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter/generate': {
      id: '/cover-letter/generate'
      path: '/cover-letter/generate'
      fullPath: '/cover-letter/generate'
      preLoaderRoute: typeof CoverLetterGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/analyze/': {
      id: '/resumes/analyze/'
      path: '/resumes/analyze'
      fullPath: '/resumes/analyze'
      preLoaderRoute: typeof ResumesAnalyzeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$resumeId/': {
      id: '/resumes/$resumeId/'
      path: '/resumes/$resumeId'
      fullPath: '/resumes/$resumeId'
      preLoaderRoute: typeof ResumesResumeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/sessions/': {
      id: '/interview/sessions/'
      path: '/interview/sessions'
      fullPath: '/interview/sessions'
      preLoaderRoute: typeof InterviewSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter/$coverLetterId/': {
      id: '/cover-letter/$coverLetterId/'
      path: '/cover-letter/$coverLetterId'
      fullPath: '/cover-letter/$coverLetterId'
      preLoaderRoute: typeof CoverLetterCoverLetterIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/new/': {
      id: '/applications/new/'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof ApplicationsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/': {
      id: '/applications/$applicationId/'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify/': {
      id: '/(auth)/verify/'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof authVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register/': {
      id: '/(auth)/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login/': {
      id: '/(auth)/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password/': {
      id: '/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter/$coverLetterId/edit': {
      id: '/cover-letter/$coverLetterId/edit'
      path: '/cover-letter/$coverLetterId/edit'
      fullPath: '/cover-letter/$coverLetterId/edit'
      preLoaderRoute: typeof CoverLetterCoverLetterIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications/$applicationId/edit': {
      id: '/applications/$applicationId/edit'
      path: '/applications/$applicationId/edit'
      fullPath: '/applications/$applicationId/edit'
      preLoaderRoute: typeof ApplicationsApplicationIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password/$token': {
      id: '/(auth)/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof authResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoverLetterGenerateRoute: CoverLetterGenerateRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
  CoverLetterIndexRoute: CoverLetterIndexRoute,
  ResumesIndexRoute: ResumesIndexRoute,
  authResetPasswordTokenRoute: authResetPasswordTokenRoute,
  ApplicationsApplicationIdEditRoute: ApplicationsApplicationIdEditRoute,
  CoverLetterCoverLetterIdEditRoute: CoverLetterCoverLetterIdEditRoute,
  authForgotPasswordIndexRoute: authForgotPasswordIndexRoute,
  authLoginIndexRoute: authLoginIndexRoute,
  authRegisterIndexRoute: authRegisterIndexRoute,
  authVerifyIndexRoute: authVerifyIndexRoute,
  ApplicationsApplicationIdIndexRoute: ApplicationsApplicationIdIndexRoute,
  ApplicationsNewIndexRoute: ApplicationsNewIndexRoute,
  CoverLetterCoverLetterIdIndexRoute: CoverLetterCoverLetterIdIndexRoute,
  InterviewSessionsIndexRoute: InterviewSessionsIndexRoute,
  ResumesResumeIdIndexRoute: ResumesResumeIdIndexRoute,
  ResumesAnalyzeIndexRoute: ResumesAnalyzeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
